spring:
  application:
    name: springboot

#DB설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: esumtech1@#$5

  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

# true 설정 시 JPA 쿼리문 확인 가능
#  jpa:
#    show-sql: true

# DDL 정의 시 DB의 고유 기능을 사용 가능
  hibernate:
    ddl-auto: update
  
  thymeleaf:
    enabled: true
    cache: false
    prefix: file:src/main/resources/templates/
    suffix: .html
    check-template-location: true

  devtools:
    restart:
      exclude: true

# JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여줌

# Mybatis 설정 정보
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboot.board

# application.yml 에서 로깅 설정
logging:
  level:
    com.example.springboot: debug

# context path 설정
server:
  servlet:
    context-path: ''