spring:
  profiles:
    active: local

---

spring:
  application:
    name: springboot
  config:
    activate:
      on-profile: local

#DB설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/proj?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: esumtech1@#$5

    hikari:
      connection-timeout: 20000 #20초: DB 연결 최대 대기 시간
      idle-timeout: 30000 #30초 : pool에 일을 안하는 커넥션을 유지하는 시간
      max-lifetime: 230000 #20초 DB 28.8초에서 5초 짧께 커넥션 제거
      auto-commit: true # 자동 커밋

  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

# true 설정 시 JPA 쿼리문 확인 가능
#  jpa:
#    show-sql: true

# DDL 정의 시 DB의 고유 기능을 사용 가능
  hibernate:
    ddl-auto: update
  
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

  devtools:
    restart:
      exclude: true

#--jsp setting--
#spring.mvc.view.prefix=/WEB-INF/jsp/
#spring.mvc.view.suffix=.jsp
#spring.thymeleaf.enabled=false

# JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여줌

# Mybatis 설정 정보
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.springboot.board

# application.yml 에서 로깅 설정
logging:
  level:
    com.example.springboot: debug

# context path 설정
server:
  servlet:
    context-path: ''
  port: 8080

---

## do other profile setting